#!/bin/bash
if [ -z $1 ] 
  then
  echo "No input parameter"
  exit 1
fi
echo $'\033[1;33m...creating container for debian\033[0m';
lxc-create -t download -n $1 -- -d debian -r  bookworm -a amd64;
echo '\033[1;33m...end\033[0m';
exit 0
