#!/bin/bash
apt update;
echo "\033[1;33m...begin install lxc\033[0m";
apt -y install lxc iptables apparmor debootstrap dirmngr gnupg libpam-cgfs lxc-templates lxcfs openssl rsync uidmap wget btrfs-progs lvm2 python3-lxc libvirt0 bridge-utils systemd ufw ssh curl sudo;
echo "\033[1;33m...end\033[0m"